### GET n new order
GET http://localhost:3000/api/picks


### POST n new order
POST http://localhost:3000/api/picks
Content-Type: application/json

{
    "user": "123123" ,
    "match": "matchId" ,
    "pick": "pick"
}